title: This is a "blog"
author: Curt Whelan
email: curtawhelan@outlook.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the coolest website of all time. There is no website that is cooler than this one.
  You might think that you know of one but you do not. This is it. Gucci Gang.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
